#!/usr/bin/env python3
# Copyright (c) 2026 Kyber-6G Project

"""
Drone Swarm PQC Performance Analysis Framework

Parses output CSV files generated by `drone-swarm-pqc-sim.cc` and computes
statistical metrics, rendering publication-ready performance tradeoff plots.

Required Dependencies:
pip install pandas matplotlib
"""

import os
import glob
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def load_data(files):
    """Loads a list of CSV files returning a combined dataframe with metadata."""
    df_list = []
    for file in files:
        if not os.path.exists(file):
            continue
        try:
            # Filename convention: drone_swarm_metrics_{crypto}_{nodes}.csv
            parts = os.path.basename(file).split('.')[0].split('_')
            crypto = parts[3]
            nodes = int(parts[4])
            
            df = pd.read_csv(file)
            df['Crypto'] = crypto
            df['Nodes'] = nodes
            df_list.append(df)
        except Exception as e:
            print(f"Error reading {file}: {e}")
            
    if df_list:
        return pd.concat(df_list, ignore_index=True)
    return pd.DataFrame()

# ═══════════════════════════════════════════════════════════
# Graph Plotters
# ═══════════════════════════════════════════════════════════

def plot_latency_vs_nodes(df, output_dir):
    """Generates Latency vs Drone Scalability Plot"""
    plt.figure(figsize=(8, 5))
    
    subset = df[df['metric'] == 'e2e_app_latency_ms']
    
    # Needs to be grouped by nodes and crypto
    for crypto in subset['Crypto'].unique():
        crypto_data = subset[subset['Crypto'] == crypto].sort_values('Nodes')
        plt.plot(crypto_data['Nodes'], crypto_data['mean'], marker='o', label=crypto)
        
    plt.title('End-to-End Application Latency vs Swarm Size')
    plt.xlabel('Number of Drones')
    plt.ylabel('Mean E2E Latency (ms)')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'latency_vs_nodes.png'), dpi=300)
    print("Saved latency_vs_nodes.png")

def plot_overhead(df, output_dir):
    """Plots RRC Overhead Impact"""
    plt.figure(figsize=(8, 5))
    
    subset = df[df['metric'] == 'rrc_setup_size_bytes']
    if subset.empty:
        return
        
    for crypto in subset['Crypto'].unique():
        crypto_data = subset[subset['Crypto'] == crypto].sort_values('Nodes')
        plt.bar(crypto_data['Crypto'], crypto_data['mean'].iloc[0], label=crypto)
        
    plt.title('RRC Connection Setup Size Overhead')
    plt.ylabel('Payload Size (Bytes)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'rrc_overhead.png'), dpi=300)
    print("Saved rrc_overhead.png")

def plot_queueing_delay_mm1(df, output_dir):
    """Validates trace queueing behavior against M/M/1 approximation."""
    plt.figure(figsize=(8, 5))
    
    subset = df[df['metric'] == 'queueing_delay_us']
    if subset.empty:
        return
        
    for crypto in subset['Crypto'].unique():
        crypto_data = subset[subset['Crypto'] == crypto].sort_values('Nodes')
        
        # M/M/1 expected theoretical wait time: E[W] = rho / (mu - lambda)
        # Assuming arrival rate lambda scales linearly with Nodes 
        # and service rate mu represents Link Capacity / Packet Size
        # Here we plot the raw measured delay values from the tracing against node count
        plt.plot(crypto_data['Nodes'], crypto_data['mean'], marker='s', linestyle='--', label=f'{crypto} Measured')

        # Dummy theoretical curve calculation for visualization
        lam = crypto_data['Nodes'].values * 10  # arrivals/sec
        mu = 5000  # service rate
        theoretical_ew = []
        for l in lam:
            rho = l / mu
            if rho >= 1: theoretical_ew.append(float('inf'))
            else: theoretical_ew.append( (rho / (mu - l)) * 1e6 ) # us
        
        plt.plot(crypto_data['Nodes'], theoretical_ew, alpha=0.5, label=f'{crypto} M/M/1 Theoretical')
        
    plt.title('Gateway MAC Queueing Delay (M/M/1 Validation)')
    plt.xlabel('Number of Drones')
    plt.ylabel('Mean Queue Wait Time (us)')
    # Set y-axis to log scale because queue theory spikes asymptotically near saturation
    plt.yscale('log')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'queueing_delay_log.png'), dpi=300)
    print("Saved queueing_delay_log.png")

def plot_security_strength(output_dir):
    """
    Renders the theoretical security strength graph contrasting 
    Classical ECC vs LWE/Kyber vs Quantum Shor capabilities
    Shor's algorithm solves ECDLP in polynomial time O(n^3); Kyber holds exponential O(2^(0.292b)).
    """
    plt.figure(figsize=(8, 5))
    bits = np.arange(100, 1025, 50)
    
    # Simple complexity approximations
    cost_classical_ecc = 2 ** (bits / 2)       # Pollard's rho
    cost_shor_ecc = bits ** 3                  # Shor scaling
    cost_lwe_classical = 2 ** (0.292 * bits)   # Core-Sieve hardness on LWE
    cost_lwe_quantum = 2 ** (0.265 * bits)     # Grover/Sieve quantum cost
    
    plt.plot(bits, np.log2(cost_classical_ecc), label='ECC (Classical Attacker)', color='blue')
    plt.plot(bits, np.log2(cost_shor_ecc), label='ECC (Quantum Shor)', color='red', linestyle='--')
    plt.plot(bits, np.log2(cost_lwe_classical), label='LWE Kyber-Target (Classical)', color='green')
    plt.plot(bits, np.log2(cost_lwe_quantum), label='LWE Kyber-Target (Quantum)', color='purple', linestyle='--')
    
    plt.axhline(128, color='black', alpha=0.3, label='AES-128 Target Security Level')
    
    plt.title('Computational Cost Modeling: Classical vs LWE')
    plt.xlabel('Key Size Constraint / Lattice Dimension Proxy')
    plt.ylabel('log2(Operations to Break)')
    plt.ylim(0, 300)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'security_strength.png'), dpi=300)
    print("Saved security_strength.png")

def plot_crypto_energy(df, output_dir):
    """Plots the newly tracked Microjoules Energy / Memory Footprint overhead"""
    plt.figure(figsize=(10, 4))
    
    energy = df[df['metric'] == 'crypto_energy_uj']
    if energy.empty:
        return
        
    for crypto in energy['Crypto'].unique():
        crypto_data = energy[energy['Crypto'] == crypto].sort_values('Nodes')
        # Total energy loosely scales by nodes connecting
        plt.plot(crypto_data['Nodes'], crypto_data['mean'] * crypto_data['count'], marker='o', label=crypto)
        
    plt.title('Cumulative Swarm Crypto Computation Energy Overhead')
    plt.xlabel('Number of Drones (Handshakes)')
    plt.ylabel('Energy Profile (Microjoules)')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'energy_overhead.png'), dpi=300)
    print("Saved energy_overhead.png")

def plot_ber_reliability(output_dir):
    """
    Given additive noise, maps Bit Error Ratio (BER) approximations to 
    Packet Delivery Ratio (PDR) based on typical drone payload sizes.
    """
    plt.figure(figsize=(8, 5))
    
    # Eb/N0 range in dB (Signal-to-Noise Ratio proxy)
    ebno_db = np.linspace(0, 15, 100)
    ebno_linear = 10 ** (ebno_db / 10)
    
    # BPSK/QPSK theoretical BER: 0.5 * erfc(sqrt(Eb/N0))
    ber = 0.5 * math.erfc(np.sqrt(ebno_linear)) if isinstance(ebno_linear, float) else 0.5 * np.array([math.erfc(math.sqrt(x)) for x in ebno_linear])
    
    # Small Packet (Navigation = 64B) vs Large Packet (Kyber Handshake = 1184B)
    pdr_small = (1 - ber) ** (64 * 8)
    pdr_large = (1 - ber) ** (1184 * 8)
    
    plt.plot(ebno_db, pdr_small, label='Navigation PDR (64B)', color='blue')
    plt.plot(ebno_db, pdr_large, label='Kyber KEM PDR (1184B)', color='red', linestyle='--')
    
    plt.title('Link Reliability vs Additive Noise (AWGN Model)')
    plt.xlabel('Eb/N0 (dB)')
    plt.ylabel('Packet Delivery Ratio (PDR)')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'ber_reliability.png'), dpi=300)
    print("Saved ber_reliability.png")

def main():
    print("Finding drone simulation CSV files...")
    csv_files = glob.glob('drone_swarm_metrics_*.csv')
    
    if not csv_files:
        print("No CSV files found. Please run the simulation first.")
        print("Example: ./ns3 run \"drone-swarm-pqc-sim --crypto=Kyber768 --nodes=50\"")
        return
        
    print(f"Loaded {len(csv_files)} datasets.")
    df = load_data(csv_files)
    
    output_dir = 'analysis_plots'
    os.makedirs(output_dir, exist_ok=True)
    
    print("\nGenerating mathematical models and plots...")
    plot_latency_vs_nodes(df, output_dir)
    plot_overhead(df, output_dir)
    plot_queueing_delay_mm1(df, output_dir)
    plot_crypto_energy(df, output_dir)
    plot_security_strength(output_dir)
    plot_ber_reliability(output_dir)
    
    print(f"\nAnalysis complete. Plots saved to '{output_dir}/'")

if __name__ == '__main__':
    main()
